gui:
  showBottomLine: false
  scrollHeight: 20
  sidePanelWidth: 0.2
  theme:
    selectedLineBgColor:
      - '#2d2a27'
    inactiveViewSelectedLineBgColor:
      - '#2d2a27'
promptToReturnFromSubprocess: false
keybinding:
  universal:
    nextTab: L
    prevTab: H
    nextBlock-alt: J
    prevBlock-alt: K
    scrollLeft: h
    scrollRight: l
git:
  pagers:
    - pager: delta --paging=never
      # externalDiffCommand: difft --color=always --syntax-highlight=on
  commitPrefix:
    - pattern: "^[^/]+/(.+)$"  # Match anything after a slash
      replace: '[$1] '
    - pattern: "^(.+)$"         # Match the entire branch name if no slash
      replace: '[$1] '
customCommands:
  # Three-dot diff in Local Branches view
  - key: '#'
    context: 'localBranches'
    description: 'Three-dot diff: checked out...selected'
    command: 'git diff --stat -p --color=always {{.SelectedLocalBranch.Name}}...{{.CheckedOutBranch.Name}}'
    output: popup
    
  # Three-dot diff in Worktrees view
  - key: '#'
    context: 'worktrees'
    description: 'Three-dot diff: checked out...selected worktree'
    command: 'git diff --stat -p --color=always {{.SelectedWorktree.Name}}...{{.CheckedOutBranch.Branch}}'
    output: popup

  # Show gitignored files
  - key: '.'
    context: 'files'
    description: 'Show gitignored files'
    command: "git ls-files --others --ignored --exclude-standard --directory --no-empty-directory | grep -E '^[^/]+/?$'"
    output: popup
